version: '3.8'

services:
  python-metrics-app:
    build: ./metrics-generator/
    ports:
      - "9799:9799"
      - "8000:8000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alertmanager:/etc/prometheus/alertmanager

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards


  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  nimbus:
    image: storm
    command: storm nimbus
    environment:
      - NIMBUS_SEEDS=nimbus
    depends_on:
      - zookeeper
    ports:
      - "6627:6627"

  supervisor:
    image: storm
    command: storm supervisor
    volumes:
      - ./ml-anomaly-detection/target:/storm
      - ./ml-models:/storm/ml-models
      - ./supervisor:/storm/supervisor
    environment:
      - NIMBUS_SEEDS=nimbus
    depends_on:
      - nimbus
      - zookeeper

  ui:
    image: storm
    command: storm ui
    environment:
      - NIMBUS_SEEDS=nimbus
    depends_on:
      - nimbus
      - zookeeper
    ports:
      - "8080:8080"

  anomaly-exporter:
    build: ./anomaly-exporter/
    ports:
      - "12345:12345"
      - "1234:1234"
    depends_on:
      - python-metrics-app

volumes:
  grafana-storage: