global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'python-metrics-app'
    static_configs:
      - targets: ['python-metrics-app:8000']

  - job_name: 'anomaly-exporter'
    scrape_interval: 1s
    static_configs:
      - targets: ['anomaly-exporter:12345']

rule_files:
  - "alertmanager/simple-alert.yml"